name: Bug Report
description: File a bug report. This could be anything from incorrect information to an issue running a particular command.
title: "bug: <your title here>"
labels: ["bug"]
projects: ["earthernsence/2"]
assignees: 
  - earthernsence
body:
  - type: checkboxes
    attributes:
      value: Is there an existing issue for this?
      description: Please search the GitHub repository to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing, open issues.
          required: true
  - type: markdown
    attributes:
      value: Current behaviour
      description: A clear & concise description of what you're experiencing.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Expected behaviour
      description: A clear & concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes: 
      value: Suggested resolution
      description: (Optional) A proposed solution to the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Anything else?
      description: (Optional) Use this area for screenshots or other helpful information.
    validations:
      required: false