name: Command Suggestion
description: Suggest a new command, including any subcommands, options, etc.
title: "suggestion(command): <your title here>"
labels: ["command suggestion"]
projects: ["earthernsence/2"]
assignees: 
  - earthernsence
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search the GitHub repository to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing, open issues.
          required: true
  - type: textarea
    attributes:
      label: Command structure
      description: Provide a general outline of what the command should be. This can be a name or a description, as well as any subcommands or options that would be necessary.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear & concise description of possible command output.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: (Optional) Use this area for screenshots or other helpful information.
    validations:
      required: false